# Generated by Django 4.2.5 on 2024-01-24 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stories',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='stories.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='stories',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='stories.tag', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='stories',
            index=models.Index(fields=['-time_create'], name='stories_sto_time_cr_cea149_idx'),
        ),
    ]
