# Generated by Django 4.2.5 on 2024-01-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_stories_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
